[package]
name = "dq3"
version = "0.1.0"
authors = ["Maru0137 <maru40137@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
num = "0.2.1"
gnuplot = "0.0.35"
plotlib = "0.5.1"
