name: Build and Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-and-test-native:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build and run tests
      run: cargo test --lib --verbose
  
  build-and-test-wasm:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build and run tests
      run: cargo test --lib --target wasm32-unknown-unknown --verbose
    
  wasm-build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - uses: jetli/wasm-pack-action@v0.3.0
    - name: Build
      run: wasm-pack build
